number:
  cod: 4
some:
  message:
    config: hello from config file
spring:
  datasource:
    username: root
    url: jdbc:mysql://mysql-container/db_decompras?createDatabaseIfNotExist=true&useSSL=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

