server:
  port: ${PORT:8080}
number:
  cod: 4
some:
  message:
    config: hello from config file
spring:
  datasource:
    username: root
    url: jdbc:mysql://monorail.proxy.rlwy.net:37959/db_decompras?createDatabaseIfNotExist=true&useSSL=true
    password: AEfHHfB-aG1-G4-fH3FGdeAE1hbE4G2F
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

